export const REGISTER_RESET_FIELDS = '[REGISTER] RESET_FIELDS';
export const REGISTER_USER_CHANGE_NAME = '[REGISTER] USER_CHANGE_NAME';
export const REGISTER_USER_CHANGE_EMAIL = '[REGISTER] USER_CHANGE_EMAIL';
export const REGISTER_USER_CREATE_ACCOUNT = '[REGISTER] USER_CREATE_ACCOUNT';
export const REGISTER_USER_CHANGE_PASSWORD = '[REGISTER] USER_CHANGE_PASSWORD';
export const REGISTER_USER_CREATE_ACCOUNT_FAILURE = '[REGISTER] USER_CREATE_ACCOUNT_FAILURE';
export const REGISTER_USER_CREATE_ACCOUNT_SUCCESS = '[REGISTER] USER_CREATE_ACCOUNT_SUCCESS';
