export const AUTH_SET_USER = '[AUTH] SET_USER';
export const AUTH_USER_LOGIN = '[AUTH] USER_LOGIN';
export const AUTH_USER_LOGOUT = '[AUTH] USER_LOGOUT';
export const AUTH_RESET_FIELDS = '[AUTH] RESET_FIELDS';
export const AUTH_USER_CHANGE_EMAIL = '[AUTH] USER_CHANGE_EMAIL';
export const AUTH_USER_LOGIN_FAILURE = '[AUTH] USER_LOGIN_FAILURE';
export const AUTH_USER_LOGIN_SUCCESS = '[AUTH] USER_LOGIN_SUCCESS';
export const AUTH_USER_CHANGE_PASSWORD = '[AUTH] USER_CHANGE_PASSWORD';
